server:
  port: 0

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/local
      database: local
  application:
    name: product-management

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

logging:
  file:
    name: logs/application.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
  level:
    com.netflix.discovery: DEBUG
    com.netflix.eureka: DEBUG