apiVersion: v1
kind: PersistentVolume
metadata:
  name: order-management-pv
  namespace: default
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /Users/adriancyago/Projects/advanced-spring-java-dev-training/logs/order-management
  storageClassName: standard
  persistentVolumeReclaimPolicy: Retain
