apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: order-management-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard
