server:
  port: 8081

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: guest
    username: postgres
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
  application:
    name: order-management

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

feign:
  client:
    config:
      default:
        loadBalancer:
          enabled: true

load-balancers-for: >
  product-management

logging:
  level:
    com.netflix.discovery: DEBUG
    com.netflix.eureka: DEBUG